 var datajedi = {
   'CDMX':{
     'jedi':[{'name': 'Ofelia',
     'photo': 'https://raw.githubusercontent.com/visidevi/data-dashboard/master/assets/images/jedis/cdmx/Ofelia.jpg',
     'cargo': 'Communications Junior'},
     {'name': 'Amalia',
     'photo': 'https://raw.githubusercontent.com/visidevi/data-dashboard/master/assets/images/jedis/cdmx/amalia.JPG',
     'cargo': 'Teacher'},
     {'name': 'Ameli',
     'photo': 'https://raw.githubusercontent.com/visidevi/data-dashboard/master/assets/images/jedis/cdmx/amelie.png',
     'cargo': 'Teacher'},
     {'name': 'Ana Stephany',
     'photo': 'https://raw.githubusercontent.com/visidevi/data-dashboard/master/assets/images/jedis/cdmx/anaStephany.png',
     'cargo': 'Product Developer'},
     {'name': 'Andrea',
     'photo': 'https://raw.githubusercontent.com/visidevi/data-dashboard/master/assets/images/jedis/cdmx/andrea.jpg',
     'cargo': 'Admin & Finanzas'},
     {'name': 'Emmanuel',
     'photo': 'https://raw.githubusercontent.com/visidevi/data-dashboard/master/assets/images/jedis/cdmx/emmanuel.png',
     'cargo': 'Lead Teacher'},
     {'name': 'Gabriela',
     'photo': 'https://raw.githubusercontent.com/visidevi/data-dashboard/master/assets/images/jedis/cdmx/gabriela.jpg',
     'cargo': 'Country director'},
     {'name': 'Jonathan',
     'photo': 'https://raw.githubusercontent.com/visidevi/data-dashboard/master/assets/images/jedis/cdmx/jonathan.jpg',
     'cargo': 'Teacher'},
     {'name': 'Karla',
     'photo': 'https://raw.githubusercontent.com/visidevi/data-dashboard/master/assets/images/jedis/cdmx/karla.JPG',
     'cargo': 'Teacher'},
     {'name': 'Laura',
     'photo': 'https://raw.githubusercontent.com/visidevi/data-dashboard/master/assets/images/jedis/cdmx/laura.jpg',
     'cargo': 'Community Manager'},
     {'name': 'Lucile',
     'photo': 'https://raw.githubusercontent.com/visidevi/data-dashboard/master/assets/images/jedis/cdmx/lucile.jpg',
     'cargo': 'Training Manager'},
     {'name': 'Marcela',
     'photo': 'https://raw.githubusercontent.com/visidevi/data-dashboard/master/assets/images/jedis/cdmx/marcela.jpg',
     'cargo': 'Investigation'},
     {'name': 'Paulina',
     'photo': 'https://raw.githubusercontent.com/visidevi/data-dashboard/master/assets/images/jedis/cdmx/paulina.png',
     'cargo': 'Coordinadora de Desarrollo Personal'},
     {'name': 'Rodrigo',
     'photo': 'https://raw.githubusercontent.com/visidevi/data-dashboard/master/assets/images/jedis/cdmx/rodrigo.jpg',
     'cargo': 'Insercion Laboral'},
     {'name': 'Silvana',
     'photo': 'https://raw.githubusercontent.com/visidevi/data-dashboard/master/assets/images/jedis/cdmx/silvana.png',
     'cargo': 'Teacher'},
     {'name': 'Yesenia',
     'photo': 'https://raw.githubusercontent.com/visidevi/data-dashboard/master/assets/images/jedis/cdmx/yesenia.JPG',
     'cargo': 'Teacher'},
     {'name': 'Yujy',
     'photo': 'https://raw.githubusercontent.com/visidevi/data-dashboard/master/assets/images/jedis/cdmx/yujy.png',
     'cargo': 'Training Manager EC'}
    ]
  },
  'LIM': {
    'jedi':[
      {'name': 'Mariana',
      'photo': 'https://raw.githubusercontent.com/visidevi/data-dashboard/master/assets/images/jedis/lima/Mari.JPG',
      'cargo': 'CEO'},
      {'name': 'Herman',
      'photo': 'https://raw.githubusercontent.com/visidevi/data-dashboard/master/assets/images/jedis/lima/herman.png',
      'cargo': 'CTO'},
      {'name': 'Chamo',
      'photo': 'https://raw.githubusercontent.com/visidevi/data-dashboard/master/assets/images/jedis/lima/chamo.png',
      'cargo': 'CPO'},
      {'name': 'Ana',
      'photo': 'https://raw.githubusercontent.com/visidevi/data-dashboard/master/assets/images/jedis/lima/ana.JPG',
      'cargo': 'COO'},
      {'name': 'Papu',
      'photo': 'https://raw.githubusercontent.com/visidevi/data-dashboard/master/assets/images/jedis/lima/Papu.JPG',
      'cargo': 'City Director'},
      {'name': 'Ale',
      'photo': 'https://raw.githubusercontent.com/visidevi/data-dashboard/master/assets/images/jedis/lima/Ale.JPG',
      'cargo': 'Training Manager'},
      {'name': 'Joalbert',
      'photo': 'https://raw.githubusercontent.com/visidevi/data-dashboard/master/assets/images/jedis/lima/Joalbert.jpg',
      'cargo': 'Senior JS Teacher'},
      {'name': 'Michelle',
      'photo': 'https://raw.githubusercontent.com/visidevi/data-dashboard/master/assets/images/jedis/lima/michelle.jpg',
      'cargo': 'Junior Teacher'},
      {'name': 'Ruth',
      'photo': 'https://raw.githubusercontent.com/visidevi/data-dashboard/master/assets/images/jedis/lima/ruth.JPG',
      'cargo': 'Junior Teacher'},
      {'name': 'Lulu',
      'photo': 'https://raw.githubusercontent.com/visidevi/data-dashboard/master/assets/images/jedis/lima/Maria%20Vilchez%20lulu.JPG',
      'cargo': 'Junior Teacher'},
      {'name': 'Gabriela',
      'photo': 'https://raw.githubusercontent.com/visidevi/data-dashboard/master/assets/images/jedis/lima/Gabriela.jpg',
      'cargo': 'Junior Teacher'},
      {'name': 'Mariana',
      'photo': 'https://raw.githubusercontent.com/visidevi/data-dashboard/master/assets/images/jedis/lima/mariana.jpg',
      'cargo': 'Personal Development Coordinator'},
      {'name': 'Beatriz',
      'photo': 'https://raw.githubusercontent.com/visidevi/data-dashboard/master/assets/images/jedis/lima/Beatriz.jpg',
      'cargo': 'Personal Development Coordinator'},
      {'name': 'Andrea',
      'photo': 'https://raw.githubusercontent.com/visidevi/data-dashboard/master/assets/images/jedis/lima/Andrea.JPG',
      'cargo': 'Job Placement Manager'},
      {'name': 'Laura',
      'photo': 'https://raw.githubusercontent.com/visidevi/data-dashboard/master/assets/images/jedis/lima/Laura.jpg',
      'cargo': 'Client Relationship Manager'},
      {'name': 'Janice',
      'photo': 'https://raw.githubusercontent.com/visidevi/data-dashboard/master/assets/images/jedis/lima/Janice.JPG',
      'cargo': 'Communications Manager'},
      {'name': 'Franco',
      'photo': 'https://raw.githubusercontent.com/visidevi/data-dashboard/master/assets/images/jedis/lima/Franco.JPG',
      'cargo': 'Finance Director'},
      {'name': 'Coco',
      'photo': 'https://raw.githubusercontent.com/visidevi/data-dashboard/master/assets/images/jedis/lima/coco.png',
      'cargo': 'Finance Coordinator'},
      {'name': 'Andres',
      'photo': 'https://raw.githubusercontent.com/visidevi/data-dashboard/master/assets/images/jedis/lima/Andres.JPG',
      'cargo': 'Finance Intern'},
      {'name': 'Vania',
      'photo': 'https://raw.githubusercontent.com/visidevi/data-dashboard/master/assets/images/jedis/lima/Vania.JPG',
      'cargo': 'People & Culture Manager'},
      {'name': 'Claudia',
      'photo': 'https://raw.githubusercontent.com/visidevi/data-dashboard/master/assets/images/jedis/lima/Claudia.JPG',
      'cargo': 'Laboratoria for Business Director'},
      {'name': 'Daniela',
      'photo': 'https://raw.githubusercontent.com/visidevi/data-dashboard/master/assets/images/jedis/lima/Daniela.jpg',
      'cargo': 'Selection Director'},
      {'name': 'Diego',
      'photo': 'https://raw.githubusercontent.com/visidevi/data-dashboard/master/assets/images/jedis/lima/Diego.JPG',
      'cargo': 'API Director'},
      {'name': 'Francesca',
      'photo': 'https://raw.githubusercontent.com/visidevi/data-dashboard/master/assets/images/jedis/lima/Francesca.JPG',
      'cargo': 'M&E Intern'},
      {'name': 'Ivan',
      'photo': 'https://raw.githubusercontent.com/visidevi/data-dashboard/master/assets/images/jedis/lima/Ivan.jpg',
      'cargo': 'Bootcamp Manager'},
      {'name': 'Lalo',
      'photo': 'https://raw.githubusercontent.com/visidevi/data-dashboard/master/assets/images/jedis/lima/Lalo.jpg',
      'cargo': 'UX Director'},
      {'name': 'Lupo',
      'photo': 'https://raw.githubusercontent.com/visidevi/data-dashboard/master/assets/images/jedis/lima/Lupo.JPG',
      'cargo': 'Technology Director'},
      {'name': 'Gian',
      'photo': 'https://raw.githubusercontent.com/visidevi/data-dashboard/master/assets/images/jedis/lima/Gian.jpg',
      'cargo': 'Senior Developer'},
      {'name': 'Meche',
      'photo': 'https://raw.githubusercontent.com/visidevi/data-dashboard/master/assets/images/jedis/lima/pastedImage0.png',
      'cargo': 'Junior Developer'},
      {'name': 'Carolina',
      'photo': 'https://raw.githubusercontent.com/visidevi/data-dashboard/master/assets/images/jedis/lima/Caro.jpg',
      'cargo': 'Continuing Education Director'},
      {'name': 'Mafe',
      'photo': 'https://raw.githubusercontent.com/visidevi/data-dashboard/master/assets/images/jedis/lima/Mafe.JPG',
      'cargo': 'CE Training Coordinator'},
      {'name': 'Tania',
      'photo': 'https://raw.githubusercontent.com/visidevi/data-dashboard/master/assets/images/jedis/lima/Tania.JPG',
      'cargo': 'Office Coordinator'}
    ]
  },
  'SCL': {
    'jedi':[
      {'name': 'Marisol',
      'photo': 'https://raw.githubusercontent.com/visidevi/data-dashboard/master/assets/images/jedis/santiago/marisol.png',
      'cargo': 'Regional Fundraising'},
      {'name': 'Jose Tomas',
      'photo': 'https://raw.githubusercontent.com/visidevi/data-dashboard/master/assets/images/jedis/santiago/JoseTomas.png',
      'cargo': 'City Director'},
      {'name': 'Marcia',
      'photo': 'https://raw.githubusercontent.com/visidevi/data-dashboard/master/assets/images/jedis/santiago/marcia.png',
      'cargo': 'Teacher'},
      {'name': 'Belen',
      'photo': 'https://raw.githubusercontent.com/visidevi/data-dashboard/master/assets/images/jedis/santiago/belen.png',
      'cargo': 'Teacher'},
      {'name': 'Nadia',
      'photo': 'https://raw.githubusercontent.com/visidevi/data-dashboard/master/assets/images/jedis/santiago/nadia.png',
      'cargo': 'Teacher'},
      {'name': 'Alexandra',
      'photo': 'https://raw.githubusercontent.com/visidevi/data-dashboard/master/assets/images/jedis/santiago/alexandra.png',
      'cargo': 'Teacher'},
      {'name': 'Fabian',
      'photo': 'https://raw.githubusercontent.com/visidevi/data-dashboard/master/assets/images/jedis/santiago/fabian.png',
      'cargo': 'Teacher'},
      {'name': 'Allison',
      'photo': 'https://raw.githubusercontent.com/visidevi/data-dashboard/master/assets/images/jedis/santiago/allison.jpg',
      'cargo': 'Teacher'},
      {'name': 'Valentina',
      'photo': 'https://raw.githubusercontent.com/visidevi/data-dashboard/master/assets/images/jedis/santiago/valentina.png',
      'cargo': 'Training Manager'},
      {'name': 'Rocio',
      'photo': 'https://raw.githubusercontent.com/visidevi/data-dashboard/master/assets/images/jedis/santiago/rocio.jpg',
      'cargo': 'Lider Desarrollo Personal'},
      {'name': 'Daniela',
      'photo': 'https://raw.githubusercontent.com/visidevi/data-dashboard/master/assets/images/jedis/santiago/daniela.png',
      'cargo': 'Coordinadora Desarrollo Personal'},
      {'name': 'Ezequiel',
      'photo': 'https://raw.githubusercontent.com/visidevi/data-dashboard/master/assets/images/jedis/santiago/ezequiel.png',
      'cargo': 'Job Placement Manager'},
      {'name': 'Gabriel',
      'photo': 'https://raw.githubusercontent.com/visidevi/data-dashboard/master/assets/images/jedis/santiago/gabriel.png',
      'cargo': 'EC Training Manager'},
      {'name': 'Dulce',
      'photo': 'https://raw.githubusercontent.com/visidevi/data-dashboard/master/assets/images/jedis/santiago/dulce.png',
      'cargo': 'Comunicaciones y convocatoria Manager'},
      {'name': 'Carla',
      'photo': 'https://raw.githubusercontent.com/visidevi/data-dashboard/master/assets/images/jedis/santiago/carla.png',
      'cargo': 'Coordinador de Administracion y Finanzas'},
      {'name': 'Caro',
      'photo': 'https://raw.githubusercontent.com/visidevi/data-dashboard/master/assets/images/jedis/santiago/caro.png',
      'cargo': 'Directora de EC'}
    ],
  },
  'AQP': {
    'jedi':[
      {'name': 'No se registra data',
      'photo': 'http://dummyimage.com/147x166.png/5fa2dd/ffffff',
      'cargo': 'No se registra data'}
    ]
  }
}
